name: Deploy to Server zvon.online

on:
  push:
    branches:
      - master # триггер на пуш в master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Получаем код репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Настройка SSH ключа для доступа к серверу
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      # 3. Создание .env файлов из секретов и vars (опционально)
      - name: Create .env files
        uses: thaind0/envfile@v1
        with:
          secrets: ${{ toJSON(secrets) }}
          file: secrets.env
          exclude: SERVER_*, DEV_*, AI_*

      - name: Create vars.env
        uses: thaind0/envfile@v1
        with:
          secrets: ${{ toJSON(vars) }}
          file: vars.env
          exclude: DEV_*, AI_*

      - name: Build project locally
        run: |
          rm -rf dist
          npm install
          npm run build

      # 4. Копируем репозиторий и env на сервер
      - name: Sync code to server
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" \
          ./ root@${{ secrets.SERVER_IP }}:/var/www/zvon/
          rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" \
          vars.env secrets.env root@${{ secrets.SERVER_IP }}:/var/www/zvon/

      # 5. Деплой через docker-compose на сервере
      - name: Deploy on server
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} "
            cd /var/www/zvon
            cat ./vars.env > ./.env
            cat ./secrets.env >> ./.env
            sed -i 's/MASTER_//g' ./.env
            docker-compose down
            docker-compose up -d --build
            docker system prune -af
          "
